### ISSUE TITLE
偶遇求个联系方式

### ISSUE THREAD

**Issue by loyinglin** [dengzemiao/OCDZMeBookRead#6]
你好，在偶然间见到你的这个工程，感觉代码实现风格和质量非常高；
望QQ联系一下，交流交流。 Q号，490094640

**Comment by dengzemiao** [comment]
DZMeBookRead 有Q群

**Comment by loyinglin** [comment]
请问qq群号是多少？

**Comment by loyinglin** [comment]
有个困扰，想请问下：
有一种情况是CoreText在分页的时候，段落A被分在两个页面1、2中。
因为我没有用把\n换成space+\n，而是设置了首行缩进2个字符，那么页面2的段落A剩余部分内容也会进行首行缩进。
请问这个问题有没有解决方案？

**Comment by dengzemiao** [comment]
那是你首行缩进没做好  理论上不应该使用首行缩进 而是使用正常的文章排版 ，这个你可以看看我demo里面是怎么做的。

**Comment by dengzemiao** [comment]
技术QQ群:52181885 （入群需要回答问题：常用的网络请求框架? 有的QQ版本不显示问题 已经出现过这样的情况 所以入群自己填上答案就行 防止广告之类的人进入）

**Comment by dengzemiao** [comment]
我觉得这个BUG你就好好的看下我的demo 理解之后在去解决你现在的这个问题。

**Comment by cuiyu8580** [comment]
不能评论了？

**Comment by cuiyu8580** [comment]
如果你有幸看到这条评论，那么关于分页首行缩进的问题即将解决了。其实作者知道这个问题，但是没有说的那么清楚，但是看到这个问题的用户基本上都是用OC的，所以让你去看demo(swfit)，可能突然看起来会有一点点难度。
废话不多说了，首先不要使用段落格式中的首行缩进功能，而是应该在段首加空格，就是在\n后面加两个空格，如果你加完空格之后出现各种对不齐的奇葩问题，请下载这个demo，打开之后搜索@"// 替换换行"，然后找到demo上面的那段字符，看看demo是怎么加的，然后复制过去用，应该可以解决你80%的问题了。

**Comment by dengzemiao** [comment]
@loyinglin  有BUG请联系我 技术QQ群:52181885 （入群需要回答问题：常用的网络请求框架? 有的QQ版本不显示问题 已经出现过这样的情况 所以入群自己填上答案就行 防止广告之类的人进入）
